# Site settings
title:       程序猿__int64Ago
email:       int64ago@gmail.com
author:      Cody Chan
description: "程序猿__int64Ago -- Keep It Simple, Stupid!"
baseurl:     ""
url:         "https://int64ago.org"

animated:           true
disqus_shortname: int64ago

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
permalink:    pretty
paginate:     8
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
